"""empty message

Revision ID: 9818fca52c65
Revises: a6d1fcb365a5
Create Date: 2024-12-02 20:35:20.954895

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9818fca52c65"
down_revision: Union[str, None] = "a6d1fcb365a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat", schema=None) as batch_op:
        batch_op.create_unique_constraint("chat_unique_name_idx", ["name"])

    with op.batch_alter_table("location", schema=None) as batch_op:
        batch_op.create_unique_constraint("location_unique_name_idx", ["name"])

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_unique_constraint("unique_email_idx", ["email"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("chat_unique_name_idx", type_="unique")

    with op.batch_alter_table("location", schema=None) as batch_op:
        batch_op.drop_constraint("location_unique_name_idx", type_="unique")

    with op.batch_alter_table("chat", schema=None) as batch_op:
        batch_op.drop_constraint("unique_name_idx", type_="unique")

    # ### end Alembic commands ###
